import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import YAML from 'yaml';
import { validateSpecFile, type ValidationResult } from './validate.js';
import { makePolicyReport } from './policyReport.js';

export type CompileResult = ValidationResult & {
  outputDir?: string;
  specHash?: string;
  schemaVersion?: string;
  policyReportPath?: string;
  provenancePath?: string;
};

async function ensureDirReady(dir: string, opts: { clean: boolean }) {
  try {
    const st = await fs.stat(dir);
    if (st.isDirectory()) {
      if (!opts.clean) {
        throw new Error(`Output directory already exists: ${dir} (use --clean to overwrite)`);
      }
      await fs.rm(dir, { recursive: true, force: true });
    }
  } catch (e: any) {
    if (e?.code !== 'ENOENT') throw e;
  }
  await fs.mkdir(dir, { recursive: true });
}

async function writeFile(filePath: string, content: string) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

function slugify(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function headerComment(specHash: string, schemaVersion: string) {
  return `/**\n * GENERATED BY FORGE — DO NOT EDIT MANUALLY\n * SPEC_HASH: ${specHash}\n * SCHEMA_VERSION: ${schemaVersion}\n */\n\n`;
}

function backendFiles(appName: string, ctx: { specHash: string; schemaVersion: string }) {
  const H = headerComment(ctx.specHash, ctx.schemaVersion);

  const pkgName = `@vortvex/${slugify(appName)}-backend`;
  return {
    'package.json': JSON.stringify(
      {
        name: pkgName,
        private: true,
        version: '0.0.1',
        scripts: {
          start: 'node dist/main.js',
          build: 'tsc -p tsconfig.json',
          dev: 'ts-node-dev --respawn --transpile-only src/main.ts',
          test: 'node --test'
        },
        dependencies: {
          '@nestjs/common': '^10.3.10',
          '@nestjs/core': '^10.3.10',
          '@nestjs/platform-express': '^10.3.10',
          'reflect-metadata': '^0.2.2',
          rxjs: '^7.8.1'
        },
        devDependencies: {
          '@types/node': '^22.10.2',
          typescript: '^5.7.2',
          'ts-node-dev': '^2.0.0'
        }
      },
      null,
      2
    ),
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'CommonJS',
          moduleResolution: 'Node',
          outDir: 'dist',
          rootDir: 'src',
          strict: true,
          esModuleInterop: true,
          emitDecoratorMetadata: true,
          experimentalDecorators: true,
          skipLibCheck: true
        },
        include: ['src/**/*.ts']
      },
      null,
      2
    ),
    'src/main.ts': `${H}import 'reflect-metadata';\nimport { NestFactory } from '@nestjs/core';\nimport { AppModule } from './modules/app.module';\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule, { logger: ['log','error','warn'] });\n  await app.listen(process.env.PORT ? Number(process.env.PORT) : 8080);\n  console.log('backend listening');\n}\n\nbootstrap();\n`,
    'src/modules/app.module.ts': `${H}import { Module } from '@nestjs/common';\nimport { HealthController } from '../routes/health.controller';\nimport { UsersController } from '../routes/users.controller';\nimport { UsersService } from '../services/users.service';\n\n@Module({\n  controllers: [HealthController, UsersController],\n  providers: [UsersService],\n})\nexport class AppModule {}\n`,
    'src/routes/health.controller.ts': `${H}import { Controller, Get } from '@nestjs/common';\n\n@Controller('/health')\nexport class HealthController {\n  @Get()\n  get() {\n    return { ok: true };\n  }\n}\n`,
    'src/routes/users.controller.ts': `${H}import { Body, Controller, Get, Post } from '@nestjs/common';\nimport { UsersService } from '../services/users.service';\n\n@Controller('/users')\nexport class UsersController {\n  constructor(private readonly users: UsersService) {}\n\n  @Get()\n  list() {\n    return this.users.list();\n  }\n\n  @Post()\n  create(@Body() body: { email: string; role: 'admin' | 'user' }) {\n    return this.users.create(body);\n  }\n}\n`,
    'src/services/users.service.ts': `${H}import { Injectable, BadRequestException } from '@nestjs/common';\n\nexport type User = { id: string; email: string; role: 'admin' | 'user' };\n\n// MVP NOTE: in-memory store. Next step is Cloud SQL Postgres + migrations.\n@Injectable()\nexport class UsersService {\n  private users: User[] = [];\n\n  list() {\n    return this.users;\n  }\n\n  create(input: { email: string; role: 'admin' | 'user' }) {\n    const email = String(input.email || '').trim().toLowerCase();\n    if (!email) throw new BadRequestException('email required');\n    if (!['admin','user'].includes(input.role)) throw new BadRequestException('invalid role');\n\n    // Invariant: unique email\n    if (this.users.some(u => u.email === email)) throw new BadRequestException('email must be unique');\n\n    const u: User = { id: crypto.randomUUID(), email, role: input.role };\n    this.users.push(u);\n    return u;\n  }\n}\n`
  } as const;
}

function webFiles(appName: string, ctx: { specHash: string; schemaVersion: string }) {
  const H = headerComment(ctx.specHash, ctx.schemaVersion);

  const pkgName = `@vortvex/${slugify(appName)}-web`;
  return {
    'package.json': JSON.stringify(
      {
        name: pkgName,
        private: true,
        version: '0.0.1',
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start -p 3000'
        },
        dependencies: {
          next: '^14.2.35',
          react: '^18.3.1',
          'react-dom': '^18.3.1'
        },
        devDependencies: {
          typescript: '^5.7.2',
          '@types/react': '^18.3.3',
          '@types/node': '^22.10.2'
        }
      },
      null,
      2
    ),
    'next.config.mjs': `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;\n`,
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }]
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
        exclude: ['node_modules']
      },
      null,
      2
    ),
    'next-env.d.ts': `${H}/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file is generated by FORGE.\n`,
    'app/layout.tsx': `${H}export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body style={{ fontFamily: 'system-ui', padding: 24 }}>{children}</body>\n    </html>\n  );\n}\n`,
    'app/page.tsx': `${H}import Link from 'next/link';\n\nexport default function Page() {\n  return (\n    <main>\n      <h1>${appName}</h1>\n      <p>Generated by FORGE (MVP).</p>\n      <ul>\n        <li><Link href=\"/admin/users\">Admin: Create User</Link></li>\n      </ul>\n    </main>\n  );\n}\n`,
    'app/admin/users/page.tsx': `${H}'use client';\n\nimport { useState } from 'react';\n\nexport default function AdminUsers() {\n  const [email, setEmail] = useState('');\n  const [role, setRole] = useState<'admin'|'user'>('user');\n  const [result, setResult] = useState<any>(null);\n  const [error, setError] = useState<string | null>(null);\n\n  async function submit() {\n    setError(null);\n    setResult(null);\n    try {\n      const apiBase = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080';\n      const res = await fetch(apiBase + '/users', {\n        method: 'POST',\n        headers: { 'content-type': 'application/json' },\n        body: JSON.stringify({ email, role }),\n      });\n      const data = await res.json();\n      if (!res.ok) throw new Error(data?.message || 'request failed');\n      setResult(data);\n    } catch (e: any) {\n      setError(e?.message || String(e));\n    }\n  }\n\n  return (\n    <main>\n      <h1>Create User</h1>\n      <p>Flow: create_user (actor: admin)</p>\n      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>\n        <input placeholder=\"email\" value={email} onChange={(e) => setEmail(e.target.value)} />\n        <select value={role} onChange={(e) => setRole(e.target.value as any)}>\n          <option value=\"user\">user</option>\n          <option value=\"admin\">admin</option>\n        </select>\n        <button onClick={submit}>Create</button>\n      </div>\n      {error && <pre style={{ color: 'crimson' }}>{error}</pre>}\n      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}\n      <hr />\n      <p>API base: {process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080'}</p>\n    </main>\n  );\n}\n`
  } as const;
}

export async function compileFromSpecFile(
  specPath: string,
  outBaseDir: string,
  opts: { clean: boolean } = { clean: false }
): Promise<CompileResult> {
  const vr = await validateSpecFile(specPath);
  if (!vr.ok) return vr;

  const raw = await fs.readFile(specPath, 'utf8');
  const spec: any = YAML.parse(raw);

  const appName = String(spec?.app?.name || 'App');
  const outDir = path.resolve(process.cwd(), outBaseDir, slugify(appName));

  const specHash = crypto.createHash('sha256').update(raw).digest('hex');
  const schemaVersion = 'v0'; // keep stable; later: derive from schema $id/versioning

  await ensureDirReady(outDir, opts);

  const backendDir = path.join(outDir, 'backend');
  const webDir = path.join(outDir, 'web');

  // Write backend
  for (const [relPath, content] of Object.entries(backendFiles(appName, { specHash, schemaVersion }))) {
    await writeFile(path.join(backendDir, relPath), content);
  }

  // Write web
  for (const [relPath, content] of Object.entries(webFiles(appName, { specHash, schemaVersion }))) {
    await writeFile(path.join(webDir, relPath), content);
  }

  // Write manifesto
  await writeFile(
    path.join(outDir, 'FORGE_GENERATED.md'),
    `# Generated by FORGE\n\n- App: ${appName}\n- Spec: ${specPath}\n- Spec SHA256: ${specHash}\n- Schema: ${schemaVersion}\n- Generated at: ${new Date().toISOString()}\n\n## Notes\n- This output is generated. Do not edit generated code manually; change the SPEC and re-compile.\n\n## Governance\n- Policy results are recorded in POLICY_REPORT.json\n`
  );

  // Write POLICY_REPORT.json (the visible governance artifact)
  const piiFields: string[] = [];
  const entities = spec?.domain?.entities || {};
  for (const [entityName, entityDef] of Object.entries<any>(entities)) {
    const fields = entityDef?.fields || {};
    for (const [fieldName, fieldDef] of Object.entries<any>(fields)) {
      if (fieldDef?.pii === true) piiFields.push(`${entityName}.${fieldName}`);
    }
  }
  const policies = spec?.security?.policies || [];
  const hasNoPiiInLogsPolicy = policies.some((p: any) => p?.name === 'no_pii_in_logs' && p?.kind === 'logging');

  // Known advisory marker (MVP): surface as governance signal (warning, not a compile blocker).
  // We record it in POLICY_REPORT.json so the CLI can print a compact summary.
  const advisories = [
    {
      id: 'GHSA-9g9p-9gw9-jx7f',
      package: 'next',
      severity: 'high',
      title: 'Next.js vulnerable to DoS via Image Optimizer remotePatterns',
      range_affected: '>=10.0.0 <15.5.10',
      recommendation: 'Upgrade next to >= 15.5.10',
      source: 'npm audit',
      url: 'https://github.com/advisories/GHSA-9g9p-9gw9-jx7f'
    }
  ] as const;

  const policyReport = makePolicyReport({
    specHash,
    schemaVersion,
    appName,
    appVersion: String(spec?.app?.version || '0.0.0'),
    enforcementMode: 'standard',
    piiFields,
    hasNoPiiInLogsPolicy,
    advisories: advisories as any,
    warnings: vr.warnings,
    deployBlockers: []
  });

  const policyReportPath = path.join(outDir, 'POLICY_REPORT.json');
  await writeFile(policyReportPath, JSON.stringify(policyReport, null, 2) + '\n');

  // Write BUILD_PROVENANCE.json (minimal, MVP)
  const provenance = {
    forge_version: '0.1.1',
    spec_path: specPath,
    spec_hash: specHash,
    schema_version: schemaVersion,
    output_dir: outDir,
    policy_report: 'POLICY_REPORT.json',
    generated_at: new Date().toISOString()
  };
  const provenancePath = path.join(outDir, 'BUILD_PROVENANCE.json');
  await writeFile(provenancePath, JSON.stringify(provenance, null, 2) + '\n');

  return {
    ok: true,
    errors: [],
    warnings: vr.warnings,
    outputDir: outDir,
    specHash,
    schemaVersion,
    policyReportPath,
    provenancePath
  };
}
