import type { CompilerTarget, GeneratedArtifact, TargetContext } from './target.js';

function slugify(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function headerComment(specHash: string, schemaVersion: string) {
  return `/**\n * GENERATED BY FORGE — DO NOT EDIT MANUALLY\n * SPEC_HASH: ${specHash}\n * SCHEMA_VERSION: ${schemaVersion}\n */\n\n`;
}

export class BackendNestjsTarget implements CompilerTarget {
  readonly id = 'backend-nestjs';

  rootDirName() {
    return 'backend';
  }

  generate(input: { spec: any; appName: string; ctx: TargetContext }): GeneratedArtifact[] {
    const H = headerComment(input.ctx.specHash, input.ctx.schemaVersion);
    const pkgName = `@vortvex/${slugify(input.appName)}-backend`;

    return [
      {
        relPath: 'package.json',
        content: JSON.stringify(
          {
            name: pkgName,
            private: true,
            version: '0.0.1',
            scripts: {
              start: 'node dist/main.js',
              build: 'tsc -p tsconfig.json',
              dev: 'ts-node-dev --respawn --transpile-only src/main.ts',
              test: 'node --test'
            },
            dependencies: {
              '@nestjs/common': '^10.3.10',
              '@nestjs/core': '^10.3.10',
              '@nestjs/platform-express': '^10.3.10',
              'reflect-metadata': '^0.2.2',
              rxjs: '^7.8.1'
            },
            devDependencies: {
              '@types/node': '^22.10.2',
              typescript: '^5.7.2',
              'ts-node-dev': '^2.0.0'
            }
          },
          null,
          2
        )
      },
      {
        relPath: 'tsconfig.json',
        content: JSON.stringify(
          {
            compilerOptions: {
              target: 'ES2022',
              module: 'CommonJS',
              moduleResolution: 'Node',
              outDir: 'dist',
              rootDir: 'src',
              strict: true,
              esModuleInterop: true,
              emitDecoratorMetadata: true,
              experimentalDecorators: true,
              skipLibCheck: true
            },
            include: ['src/**/*.ts']
          },
          null,
          2
        )
      },
      {
        relPath: 'src/main.ts',
        content: `${H}import 'reflect-metadata';\nimport { NestFactory } from '@nestjs/core';\nimport { AppModule } from './modules/app.module';\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule, { logger: ['log','error','warn'] });\n  await app.listen(process.env.PORT ? Number(process.env.PORT) : 8080);\n  console.log('backend listening');\n}\n\nbootstrap();\n`
      },
      {
        relPath: 'src/modules/app.module.ts',
        content: `${H}import { Module } from '@nestjs/common';\nimport { HealthController } from '../routes/health.controller';\nimport { UsersController } from '../routes/users.controller';\nimport { UsersService } from '../services/users.service';\n\n@Module({\n  controllers: [HealthController, UsersController],\n  providers: [UsersService],\n})\nexport class AppModule {}\n`
      },
      {
        relPath: 'src/routes/health.controller.ts',
        content: `${H}import { Controller, Get } from '@nestjs/common';\n\n@Controller('/health')\nexport class HealthController {\n  @Get()\n  get() {\n    return { ok: true };\n  }\n}\n`
      },
      {
        relPath: 'src/routes/users.controller.ts',
        content: `${H}import { Body, Controller, Get, Post } from '@nestjs/common';\nimport { UsersService } from '../services/users.service';\n\n@Controller('/users')\nexport class UsersController {\n  constructor(private readonly users: UsersService) {}\n\n  @Get()\n  list() {\n    return this.users.list();\n  }\n\n  @Post()\n  create(@Body() body: { email: string; role: 'admin' | 'user' }) {\n    return this.users.create(body);\n  }\n}\n`
      },
      {
        relPath: 'src/services/users.service.ts',
        content: `${H}import { Injectable, BadRequestException } from '@nestjs/common';\n\nexport type User = { id: string; email: string; role: 'admin' | 'user' };\n\n// MVP NOTE: in-memory store. Next step is Cloud SQL Postgres + migrations.\n@Injectable()\nexport class UsersService {\n  private users: User[] = [];\n\n  list() {\n    return this.users;\n  }\n\n  create(input: { email: string; role: 'admin' | 'user' }) {\n    const email = String(input.email || '').trim().toLowerCase();\n    if (!email) throw new BadRequestException('email required');\n    if (!['admin','user'].includes(input.role)) throw new BadRequestException('invalid role');\n\n    // Invariant: unique email\n    if (this.users.some(u => u.email === email)) throw new BadRequestException('email must be unique');\n\n    const u: User = { id: crypto.randomUUID(), email, role: input.role };\n    this.users.push(u);\n    return u;\n  }\n}\n`
      }
    ];
  }
}
