import type { CompilerTarget, GeneratedArtifact, TargetContext } from './target.js';

function slugify(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function headerComment(specHash: string, schemaVersion: string) {
  return `/**\n * GENERATED BY FORGE — DO NOT EDIT MANUALLY\n * SPEC_HASH: ${specHash}\n * SCHEMA_VERSION: ${schemaVersion}\n */\n\n`;
}

export class WebNextjsTarget implements CompilerTarget {
  readonly id = 'web-nextjs';

  rootDirName() {
    return 'web';
  }

  generate(input: { spec: any; appName: string; ctx: TargetContext }): GeneratedArtifact[] {
    const H = headerComment(input.ctx.specHash, input.ctx.schemaVersion);
    const pkgName = `@vortvex/${slugify(input.appName)}-web`;

    return [
      {
        relPath: 'package.json',
        content: JSON.stringify(
          {
            name: pkgName,
            private: true,
            version: '0.0.1',
            scripts: {
              dev: 'next dev',
              build: 'next build',
              start: 'next start -p 3000'
            },
            dependencies: {
              next: '^14.2.35',
              react: '^18.3.1',
              'react-dom': '^18.3.1'
            },
            devDependencies: {
              typescript: '^5.7.2',
              '@types/react': '^18.3.3',
              '@types/node': '^22.10.2'
            }
          },
          null,
          2
        )
      },
      {
        relPath: 'next.config.mjs',
        content: `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;\n`
      },
      {
        relPath: 'tsconfig.json',
        content: JSON.stringify(
          {
            compilerOptions: {
              target: 'ES2022',
              lib: ['dom', 'dom.iterable', 'esnext'],
              allowJs: false,
              skipLibCheck: true,
              strict: true,
              noEmit: true,
              esModuleInterop: true,
              module: 'esnext',
              moduleResolution: 'bundler',
              resolveJsonModule: true,
              isolatedModules: true,
              jsx: 'preserve',
              incremental: true,
              plugins: [{ name: 'next' }]
            },
            include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
            exclude: ['node_modules']
          },
          null,
          2
        )
      },
      {
        relPath: 'next-env.d.ts',
        content: `${H}/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file is generated by FORGE.\n`
      },
      {
        relPath: 'app/layout.tsx',
        content: `${H}export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body style={{ fontFamily: 'system-ui', padding: 24 }}>{children}</body>\n    </html>\n  );\n}\n`
      },
      {
        relPath: 'app/page.tsx',
        content: `${H}import Link from 'next/link';\n\nexport default function Page() {\n  return (\n    <main>\n      <h1>${input.appName}</h1>\n      <p>Generated by FORGE (MVP).</p>\n      <ul>\n        <li><Link href=\"/admin/users\">Admin: Create User</Link></li>\n      </ul>\n    </main>\n  );\n}\n`
      },
      {
        relPath: 'app/admin/users/page.tsx',
        content: `${H}'use client';\n\nimport { useState } from 'react';\n\nexport default function AdminUsers() {\n  const [email, setEmail] = useState('');\n  const [role, setRole] = useState<'admin'|'user'>('user');\n  const [result, setResult] = useState<any>(null);\n  const [error, setError] = useState<string | null>(null);\n\n  async function submit() {\n    setError(null);\n    setResult(null);\n    try {\n      const apiBase = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080';\n      const res = await fetch(apiBase + '/users', {\n        method: 'POST',\n        headers: { 'content-type': 'application/json' },\n        body: JSON.stringify({ email, role }),\n      });\n      const data = await res.json();\n      if (!res.ok) throw new Error(data?.message || 'request failed');\n      setResult(data);\n    } catch (e: any) {\n      setError(e?.message || String(e));\n    }\n  }\n\n  return (\n    <main>\n      <h1>Create User</h1>\n      <p>Flow: create_user (actor: admin)</p>\n      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>\n        <input placeholder=\"email\" value={email} onChange={(e) => setEmail(e.target.value)} />\n        <select value={role} onChange={(e) => setRole(e.target.value as any)}>\n          <option value=\"user\">user</option>\n          <option value=\"admin\">admin</option>\n        </select>\n        <button onClick={submit}>Create</button>\n      </div>\n      {error && <pre style={{ color: 'crimson' }}>{error}</pre>}\n      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}\n      <hr />\n      <p>API base: {process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080'}</p>\n    </main>\n  );\n}\n`
      }
    ];
  }
}
