import fs from 'node:fs/promises';
import path from 'node:path';
import { backendFiles, webFiles, outputDirForApp } from './templates.js';

async function ensureDirReady(dir: string, opts: { clean: boolean }) {
  try {
    const st = await fs.stat(dir);
    if (st.isDirectory()) {
      if (!opts.clean) {
        throw new Error(`Output directory already exists: ${dir} (use --clean to overwrite)`);
      }
      await fs.rm(dir, { recursive: true, force: true });
    }
  } catch (e: any) {
    if (e?.code !== 'ENOENT') throw e;
  }
  await fs.mkdir(dir, { recursive: true });
}

async function writeFile(filePath: string, content: string) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

export type GenerateResult = {
  outDir: string;
  policyReportPath: string;
  provenancePath: string;
};

export async function generateTargets(input: {
  outBaseDir: string;
  appName: string;
  specPath: string;
  specHash: string;
  schemaVersion: string;
  clean: boolean;
}): Promise<{ outDir: string }> {
  const outDir = outputDirForApp(input.outBaseDir, input.appName);
  await ensureDirReady(outDir, { clean: input.clean });

  const backendDir = path.join(outDir, 'backend');
  const webDir = path.join(outDir, 'web');

  for (const [relPath, content] of Object.entries(backendFiles(input.appName, { specHash: input.specHash, schemaVersion: input.schemaVersion }))) {
    await writeFile(path.join(backendDir, relPath), content);
  }

  for (const [relPath, content] of Object.entries(webFiles(input.appName, { specHash: input.specHash, schemaVersion: input.schemaVersion }))) {
    await writeFile(path.join(webDir, relPath), content);
  }

  return { outDir };
}

export async function writeForgeGeneratedManifest(input: {
  outDir: string;
  appName: string;
  specPath: string;
  specHash: string;
  schemaVersion: string;
  buildTime: string;
}) {
  await writeFile(
    path.join(input.outDir, 'FORGE_GENERATED.md'),
    `# Generated by FORGE\n\n- App: ${input.appName}\n- Spec: ${input.specPath}\n- Spec SHA256: ${input.specHash}\n- Schema: ${input.schemaVersion}\n- Generated at: ${input.buildTime}\n\n## Notes\n- This output is generated. Do not edit generated code manually; change the SPEC and re-compile.\n\n## Governance\n- Policy results are recorded in POLICY_REPORT.json\n`
  );
}
