import fs from 'node:fs/promises';
import path from 'node:path';
import { outputDirForApp } from './templates.js';
import type { CompilerTarget } from './targets/target.js';

async function ensureDirReady(dir: string, opts: { clean: boolean }) {
  try {
    const st = await fs.stat(dir);
    if (st.isDirectory()) {
      if (!opts.clean) {
        throw new Error(`Output directory already exists: ${dir} (use --clean to overwrite)`);
      }
      await fs.rm(dir, { recursive: true, force: true });
    }
  } catch (e: any) {
    if (e?.code !== 'ENOENT') throw e;
  }
  await fs.mkdir(dir, { recursive: true });
}

async function writeFile(filePath: string, content: string) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

export type GenerateResult = {
  outDir: string;
  policyReportPath: string;
  provenancePath: string;
};

export async function generateTargets(input: {
  outBaseDir: string;
  appName: string;
  spec: any;
  targets: CompilerTarget[];
  ctx: { specHash: string; schemaVersion: string; buildTime: string };
  clean: boolean;
}): Promise<{ outDir: string }> {
  const outDir = outputDirForApp(input.outBaseDir, input.appName);
  await ensureDirReady(outDir, { clean: input.clean });

  for (const t of input.targets) {
    const root = path.join(outDir, t.rootDirName());
    const artifacts = await t.generate({ spec: input.spec, appName: input.appName, ctx: input.ctx });
    for (const a of artifacts) {
      await writeFile(path.join(root, a.relPath), a.content);
    }
  }

  return { outDir };
}

export async function writeForgeGeneratedManifest(input: {
  outDir: string;
  appName: string;
  specPath: string;
  specHash: string;
  schemaVersion: string;
  buildTime: string;
}) {
  await writeFile(
    path.join(input.outDir, 'FORGE_GENERATED.md'),
    `# Generated by FORGE\n\n- App: ${input.appName}\n- Spec: ${input.specPath}\n- Spec SHA256: ${input.specHash}\n- Schema: ${input.schemaVersion}\n- Generated at: ${input.buildTime}\n\n## Notes\n- This output is generated. Do not edit generated code manually; change the SPEC and re-compile.\n\n## Governance\n- Policy results are recorded in POLICY_REPORT.json\n`
  );
}
