import path from 'node:path';

function slugify(name: string) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function headerComment(specHash: string, schemaVersion: string) {
  return `/**\n * GENERATED BY FORGE — DO NOT EDIT MANUALLY\n * SPEC_HASH: ${specHash}\n * SCHEMA_VERSION: ${schemaVersion}\n */\n\n`;
}

export function backendFiles(appName: string, ctx: { specHash: string; schemaVersion: string }) {
  const H = headerComment(ctx.specHash, ctx.schemaVersion);

  const pkgName = `@vortvex/${slugify(appName)}-backend`;
  return {
    'package.json': JSON.stringify(
      {
        name: pkgName,
        private: true,
        version: '0.0.1',
        scripts: {
          start: 'node dist/main.js',
          build: 'tsc -p tsconfig.json',
          dev: 'ts-node-dev --respawn --transpile-only src/main.ts',
          test: 'node --test'
        },
        dependencies: {
          '@nestjs/common': '^10.3.10',
          '@nestjs/core': '^10.3.10',
          '@nestjs/platform-express': '^10.3.10',
          'reflect-metadata': '^0.2.2',
          rxjs: '^7.8.1'
        },
        devDependencies: {
          '@types/node': '^22.10.2',
          typescript: '^5.7.2',
          'ts-node-dev': '^2.0.0'
        }
      },
      null,
      2
    ),
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'CommonJS',
          moduleResolution: 'Node',
          outDir: 'dist',
          rootDir: 'src',
          strict: true,
          esModuleInterop: true,
          emitDecoratorMetadata: true,
          experimentalDecorators: true,
          skipLibCheck: true
        },
        include: ['src/**/*.ts']
      },
      null,
      2
    ),
    'src/main.ts': `${H}import 'reflect-metadata';\nimport { NestFactory } from '@nestjs/core';\nimport { AppModule } from './modules/app.module';\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule, { logger: ['log','error','warn'] });\n  await app.listen(process.env.PORT ? Number(process.env.PORT) : 8080);\n  console.log('backend listening');\n}\n\nbootstrap();\n`,
    'src/modules/app.module.ts': `${H}import { Module } from '@nestjs/common';\nimport { HealthController } from '../routes/health.controller';\nimport { UsersController } from '../routes/users.controller';\nimport { UsersService } from '../services/users.service';\n\n@Module({\n  controllers: [HealthController, UsersController],\n  providers: [UsersService],\n})\nexport class AppModule {}\n`,
    'src/routes/health.controller.ts': `${H}import { Controller, Get } from '@nestjs/common';\n\n@Controller('/health')\nexport class HealthController {\n  @Get()\n  get() {\n    return { ok: true };\n  }\n}\n`,
    'src/routes/users.controller.ts': `${H}import { Body, Controller, Get, Post } from '@nestjs/common';\nimport { UsersService } from '../services/users.service';\n\n@Controller('/users')\nexport class UsersController {\n  constructor(private readonly users: UsersService) {}\n\n  @Get()\n  list() {\n    return this.users.list();\n  }\n\n  @Post()\n  create(@Body() body: { email: string; role: 'admin' | 'user' }) {\n    return this.users.create(body);\n  }\n}\n`,
    'src/services/users.service.ts': `${H}import { Injectable, BadRequestException } from '@nestjs/common';\n\nexport type User = { id: string; email: string; role: 'admin' | 'user' };\n\n// MVP NOTE: in-memory store. Next step is Cloud SQL Postgres + migrations.\n@Injectable()\nexport class UsersService {\n  private users: User[] = [];\n\n  list() {\n    return this.users;\n  }\n\n  create(input: { email: string; role: 'admin' | 'user' }) {\n    const email = String(input.email || '').trim().toLowerCase();\n    if (!email) throw new BadRequestException('email required');\n    if (!['admin','user'].includes(input.role)) throw new BadRequestException('invalid role');\n\n    // Invariant: unique email\n    if (this.users.some(u => u.email === email)) throw new BadRequestException('email must be unique');\n\n    const u: User = { id: crypto.randomUUID(), email, role: input.role };\n    this.users.push(u);\n    return u;\n  }\n}\n`
  } as const;
}

export function webFiles(appName: string, ctx: { specHash: string; schemaVersion: string }) {
  const H = headerComment(ctx.specHash, ctx.schemaVersion);

  const pkgName = `@vortvex/${slugify(appName)}-web`;
  return {
    'package.json': JSON.stringify(
      {
        name: pkgName,
        private: true,
        version: '0.0.1',
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start -p 3000'
        },
        dependencies: {
          next: '^14.2.35',
          react: '^18.3.1',
          'react-dom': '^18.3.1'
        },
        devDependencies: {
          typescript: '^5.7.2',
          '@types/react': '^18.3.3',
          '@types/node': '^22.10.2'
        }
      },
      null,
      2
    ),
    'next.config.mjs': `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;\n`,
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }]
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      },
      null,
      2
    ),
    'next-env.d.ts': `${H}/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// NOTE: This file is generated by FORGE.\n`,
    'app/layout.tsx': `${H}export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body style={{ fontFamily: 'system-ui', padding: 24 }}>{children}</body>\n    </html>\n  );\n}\n`,
    'app/page.tsx': `${H}import Link from 'next/link';\n\nexport default function Page() {\n  return (\n    <main>\n      <h1>${appName}</h1>\n      <p>Generated by FORGE (MVP).</p>\n      <ul>\n        <li><Link href=\"/admin/users\">Admin: Create User</Link></li>\n      </ul>\n    </main>\n  );\n}\n`,
    'app/admin/users/page.tsx': `${H}'use client';\n\nimport { useState } from 'react';\n\nexport default function AdminUsers() {\n  const [email, setEmail] = useState('');\n  const [role, setRole] = useState<'admin'|'user'>('user');\n  const [result, setResult] = useState<any>(null);\n  const [error, setError] = useState<string | null>(null);\n\n  async function submit() {\n    setError(null);\n    setResult(null);\n    try {\n      const apiBase = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080';\n      const res = await fetch(apiBase + '/users', {\n        method: 'POST',\n        headers: { 'content-type': 'application/json' },\n        body: JSON.stringify({ email, role }),\n      });\n      const data = await res.json();\n      if (!res.ok) throw new Error(data?.message || 'request failed');\n      setResult(data);\n    } catch (e: any) {\n      setError(e?.message || String(e));\n    }\n  }\n\n  return (\n    <main>\n      <h1>Create User</h1>\n      <p>Flow: create_user (actor: admin)</p>\n      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>\n        <input placeholder=\"email\" value={email} onChange={(e) => setEmail(e.target.value)} />\n        <select value={role} onChange={(e) => setRole(e.target.value as any)}>\n          <option value=\"user\">user</option>\n          <option value=\"admin\">admin</option>\n        </select>\n        <button onClick={submit}>Create</button>\n      </div>\n      {error && <pre style={{ color: 'crimson' }}>{error}</pre>}\n      {result && <pre>{JSON.stringify(result, null, 2)}</pre>}\n      <hr />\n      <p>API base: {process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080'}</p>\n    </main>\n  );\n}\n`
  } as const;
}

export function outputDirForApp(outBaseDir: string, appName: string) {
  return path.resolve(process.cwd(), outBaseDir, slugify(appName));
}
